/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PetIndexRouteImport } from './routes/pet/index'
import { Route as PetAddPetRouteImport } from './routes/pet/addPet'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PetIndexRoute = PetIndexRouteImport.update({
  id: '/pet/',
  path: '/pet/',
  getParentRoute: () => rootRouteImport,
} as any)
const PetAddPetRoute = PetAddPetRouteImport.update({
  id: '/pet/addPet',
  path: '/pet/addPet',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pet/addPet': typeof PetAddPetRoute
  '/pet': typeof PetIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pet/addPet': typeof PetAddPetRoute
  '/pet': typeof PetIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pet/addPet': typeof PetAddPetRoute
  '/pet/': typeof PetIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pet/addPet' | '/pet'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pet/addPet' | '/pet'
  id: '__root__' | '/' | '/pet/addPet' | '/pet/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PetAddPetRoute: typeof PetAddPetRoute
  PetIndexRoute: typeof PetIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pet/': {
      id: '/pet/'
      path: '/pet'
      fullPath: '/pet'
      preLoaderRoute: typeof PetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pet/addPet': {
      id: '/pet/addPet'
      path: '/pet/addPet'
      fullPath: '/pet/addPet'
      preLoaderRoute: typeof PetAddPetRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PetAddPetRoute: PetAddPetRoute,
  PetIndexRoute: PetIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
